// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	v1work "dark-work/service/workm/crm/api/internal/handler/v1/work"
	"dark-work/service/workm/crm/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/work/index/index",
				Handler: v1work.WorkIndexIndexHandler(serverCtx),
			},
		},
	)
}
